import { BracketsManager } from './manager';

import {
    CrudInterface,
    Database,
    Duel,
    OmitId,
    OrderingMap,
    ParticipantSlot,
    Scores,
    Side,
    StandardBracketResults,
    Storage,
    Table,
} from './types';

import {
    getWinner,
    getLoser,
    getMatchResult,
    isMatchStarted,
    isMatchCompleted,
    isMatchForfeitCompleted,
    isMatchResultCompleted,
    isMatchDrawCompleted,
    isMatchWinCompleted,
    isMatchByeCompleted,
    isMatchUpdateLocked,
    isMatchParticipantLocked,
    hasBye,
    getUpperBracketRoundCount,
    getRoundPairCount,
    getLoserRoundMatchCount,
    getLoserRoundLoserCount,
    getLowerBracketRoundCount,
    getNearestPowerOfTwo,
    minScoreToWinBestOfX,
    isRoundRobin,
    isWinnerBracket,
    isLoserBracket,
    isFinalGroup,
    getMatchLocation,
} from './helpers';

export {
    BracketsManager,
    CrudInterface,
    Database,
    Duel,
    OmitId,
    OrderingMap,
    ParticipantSlot,
    Scores,
    Side,
    StandardBracketResults,
    Storage,
    Table,
};

export const helpers = {
    getWinner,
    getLoser,
    getMatchResult,
    isMatchStarted,
    isMatchCompleted,
    isMatchForfeitCompleted,
    isMatchResultCompleted,
    isMatchDrawCompleted,
    isMatchWinCompleted,
    isMatchByeCompleted,
    isMatchUpdateLocked,
    isMatchParticipantLocked,
    hasBye,
    getUpperBracketRoundCount,
    getRoundPairCount,
    getLoserRoundMatchCount,
    getLoserRoundLoserCount,
    getLowerBracketRoundCount,
    getNearestPowerOfTwo,
    minScoreToWinBestOfX,
    isRoundRobin,
    isWinnerBracket,
    isLoserBracket,
    isFinalGroup,
    getMatchLocation,
};
